### ISSUE TITLE
Large Text

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-poison-dart-frogs#15]
## User Story
As a user, with tired eyes, I should be able to chat with large text.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Large Text"
**And** they should be able to click this checkbox
**And** when the checkbox is selected all the message text should be larger

## Dev Notes
* add a checkbox in the bootstrap settings dropdown for Large Text.
* attach an event listener to the checkbox that when activated runs a function 
* write the function ``` createLargeText ``` that will apply css class that transform the message to Large Text.

**Comment by aleshakay** [comment]
![image](https://user-images.githubusercontent.com/39807157/66966778-0c850f80-f044-11e9-8ce3-55e2838872e7.png)
