### ISSUE TITLE
Delete Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-poison-dart-frogs#16]
## User Story
As a user I should be able to delete messages.

If you are doing multiple users you should only be able to delete **your** messages

## AC
**Given** A message on your page
**Then** there should be a delete button for each message (that belongs to your user)
**And** when the button is pushed the message should no longer exist

## Dev Notes
* import the cardPrint function
* assign class name for buttons
* create function called `delete` that gets all the class names for the button and loops through it 
* get each button at that position and assign it to a variable
* add an event listener to that variable that adds `deleteClick`
* create another function called `deleteClick`
* get the innerHTML of the children and assign to variable
* create for loop and if statement, to splice the object at that position
* call in the cardPrint function

**Comment by djunaim** [comment]
![image](https://user-images.githubusercontent.com/53092019/66964646-d8f2b700-f03c-11e9-885c-5a235e02a252.png)
