### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-poison-dart-frogs#17]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `data/messages.js`
**And** when they add messages it should add them to the list

## Dev Notes
* import `data/messages.js`
* create for loop to loop through array of objects
* create div in html of where to print
* use `printToDOM` to print each card to the dom
* add scroll effect
* refer to comment below for code for cards

**Comment by djunaim** [comment]
https://getbootstrap.com/docs/4.3/components/card/#using-custom-css

**Comment by djunaim** [comment]
![image](https://user-images.githubusercontent.com/53092019/66965672-1e64b380-f040-11e9-927c-d2b2e1ec14c0.png)
