### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-poison-dart-frogs#2]
## User Story
As a user, with sensitive eyes, I should be able to chat using a dark theme.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Dark Theme"
**And** they should be able to click this checkbox
**And** when the checkbox is selected the page should show a dark theme with lightly colored text

## Dev Notes
* add a checkbox in the bootstrap settings dropdown for Dark Mode.
* attach an event listener to the checkbox that when activated runs a function
* write the aforementioned function that will apply css classes that transform the page into a dark theme.

**Comment by aleshakay** [comment]
![image](https://user-images.githubusercontent.com/39807157/66966920-9208bf80-f044-11e9-8576-e38e88908a96.png)
