### ISSUE TITLE
Seed Data

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-poison-dart-frogs#3]
## User Story
As a developer, in order to have something on the page, I would like some seed data

## AC
**Given** A developer navigated to your repo
**Then** they should see a file called `data/messages.js`
**And** this file should have seed data for 5 messages

## Dev Notes
* create an array of 5 objects with a key of message and value of lorem ipsum. Refer to value comment below for template.
* create a function that returns the array and export

**Comment by djunaim** [comment]
```
const chats = [
  {
    id: 'message1',
    message: '',
  },
];
```
