### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-poison-dart-frogs#5]
# User Story
As a user, I would like to be able to customize my theme further than just light or dark mode, for I am a complex human being and I require more than a binary selection to fully express myself aesthetically.

# AC
**WHEN** The user clicks on the settings dropdown in the navbar
**THEN** I should see an option for "Change Theme"
**AND** when clicked, a bootstrap modal should appear on the screen with two color picker fields(one for background color, and one for text color), a cancel button, and a save button
**AND** when I set the colors to my desired background and click save, the colors will be applied to the page
**AND** if I click on cancel, the modal will close and the style will not be applied 

# Dev notes
* Add a link to the bootstrap dropdown for "Change theme"
* Use `<input type="color">` for color picker elements
```html
<div>
    <input type="color" id="background" name="background"
           value="#FFFFFF">
    <label for="background">Background Color</label>
</div>

<div>
    <input type="color" id="text" name="text"
            value="#FFFFFF">
    <label for="text">Text Color</label>
</div>
```
* create a function in `src/javascripts/components/themes/themes.js` that will take the value of each input tag and apply them using the css jquery method

**Comment by aleshakay** [comment]
![image](https://user-images.githubusercontent.com/39807157/66966888-71406a00-f044-11e9-9835-89a52852ff1f.png)
